name: 'SEO Gate'
on:
    pull_request:
        paths:
            - '**/*.html'
            - '**/*.md'

jobs:
    seo-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
                run: npm ci
            - name: Build
                run: npm run build
            - name: Dotsoft SEO Check
                uses: dotsoft-org/seo-check-action@v1
                with:
                    fail_on_warning: 'true'
